Adding testing to workflow.

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -44,4 +44,9 @@ jobs:
           release-name: crazy-test
           namespace: default
         run: | 
-          kubectl get pods $(kubectl get deploy -n ${{ env.namespace }}) -n ${{ env.namespace }} -o jsonpath='{.items[*].status.containerStatuses[0].ready}'
+          if [ kubectl describe pods $(kubectl get deploy -n env.namespace) -n ${{ env.namespace }} | grep "Status" == "running" ]; then
+            echo "✅ Helm uploaded correctly, test pod is running."
+            exit 0
+          else
+            echo "❌ Helm upload failed, test pod is not running."
+            exit 1
