Adding testing to workflow.

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -46,10 +46,12 @@ jobs:
           base-chart-name: testchart # Remove appended ./
         run: | 
           chartname="${{ env.release-name }}-${{ env.base-chart-name }}"
-          echo $chartname
-          status=$(kubectl get pods metadata.name==$chartname* -o jsonpath="{.items[*]['status.phase']}")
-
-          if [[ "$status"  == "Running" ]]; then
+          pod-name=$(kubectl get pods -o jsonpath="{.items[*]['metadata.name']}")
+          
+          if [[ "$pod-name"  != "$chartname"* ]]; then
+              echo "Pod name is unexpected. Install Failed."
+              exit 1
+          elif [[kubectl get pods $pod-name -o jsonpath="{.items[0]['status.phase']}" == "Running"]]; then
               echo "✅ Helm uploaded correctly, test pod is running."
               exit 0
           else
